name: malariagen-vector-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - dask=2021.03.0
  - matplotlib
  - fsspec=0.8.7
  - gcsfs=0.7.2
  - jupyterlab
  - jupyter-book
  - gsutil
  - scikit-allel=1.3.5
  - cartopy
  - rasterio
  - bokeh=2.3.2
  - plotly=4.14.3
  - xarray=0.18.0
  - zarr=2.6.1
  - pip
  - pip:
    - malariagen_data==0.7.0
